version: "3.8"
networks:
  internet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.17.70.0/24
volumes:
  phpfpmsocket: {}
  data: {}
services:
  app:
    container_name: todolist-app
    image: todolist
    restart: unless-stopped
    working_dir: /var/www/
    build:
      context: ./
      dockerfile: Dockerfile
#      args:
#        user: $TODOLIST_SYS_USER
#        uid: $TODOLIST_SYS_UID
    environment:
      PHP_DATE_TIMEZONE: CEST
      WEB_DOCUMENT_ROOT: /var/www
      WEB_DOCUMENT_INDEX: public/index.php
      WEB_ALIAS_DOMAIN: php.todolist.dev
      PHP_DISPLAY_ERRORS: 1
      PHP_DEBUGGER: xdebug
      XDEBUG_REMOTE_HOST: $IP_HOST
      XDEBUG_REMOTE_PORT: $XDEBUG_REMOTE_PORT
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_IDE_KEY: PHPSTORM
    networks:
      internet:
        ipv4_address: $IP_PHP_FPM
        aliases:
          - php.todolist.dev
    volumes:
      - ./:/var/www:rw
  database:
    image: mysql:5.7
    container_name: todolist-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
#    volumes:
#      - ./storage/logs/:/var/log/mysql/
#      - data:/var/lib/mysql/
    networks:
      internet:
        ipv4_address: $IP_DATABASE
        aliases:
          - database.todolist.dev

